import type { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  };
}

export default async function Page() {
  return (
    <div>
      <div>main</div>
    </div>
  );
}
