import { Providers } from "@/components/client/Providers";
import { getI18n } from "@/libs/server/i18n";
import type { Metadata } from "next";
import { Welcome } from "./Welcome";

export async function generateMetadata(): Promise<Metadata> {
  const t = await getI18n();
  return {
    title: `Create Next App ${t("hello")}`,
    description: "Generated by create next app",
  };
}

export default async function Page({
  params: { locale },
}: {
  params: { locale: string };
}) {
  return (
    <div>
      <div>main</div>
      <Providers locale={locale}>
        <Welcome />
      </Providers>
    </div>
  );
}
